---
name: release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: hugoh/gh-workflows/.github/workflows/release.yml@ae1366a14513d42c78dd993d7fbb776fda2d4530 # v1.38.6
    permissions:
      contents: write
    with:
      package-command: pkl project package --output-path dist
      package-artifacts: dist/*
