---
name: release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: hugoh/gh-workflows/.github/workflows/release.yml@f44d7f8d2ae57bf084a30a36be11184e2f90321c # v1.34.3
    permissions:
      contents: write
    with:
      package-command: pkl project package --output-path dist
      package-artifacts: dist/*
