---
name: release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: hugoh/gh-workflows/.github/workflows/release.yml@0e87e19c850cf07d9e32b37416a6b60ab6a666dd # v1.38.4
    permissions:
      contents: write
    with:
      package-command: pkl project package --output-path dist
      package-artifacts: dist/*
